# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-11 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecord',
            name='class_list',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='customer',
        ),
        migrations.DeleteModel(
            name='PaymentRecord',
        ),
    ]
